[manifest]
version = "1.0.0"
priority = 0

# Sneak into the splash screen function to run last-second code
[[patches]]
[patches.pattern]
target = 'game.lua'
position = "before"
pattern = "--If the skip splash screen option is set, immediately go to the main menu here"
payload = "vallkarri.populate_crossmod_buffs()"
match_indent = true

# ... and functions that reset that code
#[[patches]]
#[patches.pattern]
#target = 'functions/button_callbacks.lua'
#position = "after"
#pattern = 'G:init_item_prototypes()'
#payload = "if vallkarri then vallkarri.populate_crossmod_buffs() end" --Don't need this for now
#match_indent = true