[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Gets added after Talisman's patch I think
# card_eval_status_text()
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "elseif eval_type == 'dollars' then"
position = "before"
payload = '''elseif eval_type == 'ee_chips' then 
	sound = 'valk_eechips'
	amt = amt
	text = localize{
        type = 'variable',
        key = 'a_valk_eechips',
        vars = {amt}
    }
	colour = G.C.DARK_EDITION
	config.type = 'fade'
	config.scale = 0.7
elseif eval_type == 'ee_mult' then 
	sound = 'valk_eemult'
	amt = amt
	text = localize{
        type = 'variable',
        key = 'a_valk_eemult',
        vars = {amt}
    }
	colour = G.C.DARK_EDITION
	config.type = 'fade'
	config.scale = 0.7
'''
match_indent = true